### ISSUE TITLE
Accessing Drush from CasperJS

### ISSUE THREAD

**Issue by kostajh** [Lullabot/casperjs_foundation#1]
Hey @juampy72, thanks for setting up this repo and for the blog post. CasperJS is a great tool for testing Drupal sites. I just wanted to mention that you might be interested in my project, [Drush REST API](https://drupal.org/project/drush-rest-api) which allows CasperJS to communicate with Drush over HTTP/WebSockets - useful if you want to validate that emails are getting set, or for setup/teardown tasks, etc.

**Comment by q0rban** [comment]
@kostajh, funny, I stumbled on your article about this earlier this week! Very fascinating stuff. :)

**Comment by davereid** [comment]
An alternative seems to be https://bitbucket.org/davereid/drush-casperjs/src/4d9f4119f830899cf9fd2c6ce4e38fa43bb8b184/drupal.js?at=master#cl-162
