### ISSUE TITLE
spaces in root path

### ISSUE THREAD

**Issue by kpzani** [Lullabot/casperjs_foundation#4]
The file testrun wont work if the root directory i.e. the current directory has spaces in it.

change to ..
echo casperjs --verbose --cookies-file=cookies.txt test --includes=common.js tests/$TEST --root="`pwd`" --url=$URL
casperjs --verbose --cookies-file=cookies.txt test --includes=common.js tests/$TEST --root="`pwd`" --url=$URL

the quotes around the pwd command work fine - tested on OSX

**Comment by juampynr** [comment]
Hi @kpzani, we moved this to a Drupal module at https://www.drupal.org/project/casperjs. Did you have a look at it? I doubt that we will put any work in this repository.

**Comment by kpzani** [comment]
Not a problem.  I just added the quotes and it all worked.  I added an issue in case anyone else encountered the same problem. :-)
